/*
 * API de Gestion des Cours en Ligne - OpenAPI 3.0
 * Ceci est une API permettant de gérer le contenu des cours en ligne. Elle expose des fonctionnalités pour créer, consulter, mettre à jour, et supprimer des cours et leurs séances. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exemple.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Cours;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CoursApi
 */
@Ignore
public class CoursApiTest {

    private final CoursApi api = new CoursApi();

    /**
     * Obtenir la liste des cours
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void coursGetTest() throws Exception {
        List<Cours> response = api.coursGet();

        // TODO: test validations
    }
    /**
     * Supprimer un cours
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void coursIdDeleteTest() throws Exception {
        String id = null;
        api.coursIdDelete(id);

        // TODO: test validations
    }
    /**
     * Obtenir un cours par son identifiant
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void coursIdGetTest() throws Exception {
        String id = null;
        Cours response = api.coursIdGet(id);

        // TODO: test validations
    }
    /**
     * Mettre à jour un cours existant
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void coursIdPutTest() throws Exception {
        Cours body = null;
        String id = null;
        api.coursIdPut(body, id);

        // TODO: test validations
    }
    /**
     * Ajouter un nouveau cours
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void coursPostTest() throws Exception {
        Cours body = null;
        api.coursPost(body);

        // TODO: test validations
    }
}
