/*
 * API de Gestion des Cours en Ligne - OpenAPI 3.0
 * Ceci est une API permettant de gérer le contenu des cours en ligne. Elle expose des fonctionnalités pour créer, consulter, mettre à jour, et supprimer des cours et leurs séances. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exemple.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Seance;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SeancesApi
 */
@Ignore
public class SeancesApiTest {

    private final SeancesApi api = new SeancesApi();

    /**
     * Obtenir la liste des séances d&#x27;un cours
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void coursIdSeancesGetTest() throws Exception {
        String id = null;
        List<Seance> response = api.coursIdSeancesGet(id);

        // TODO: test validations
    }
}
