# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Seance(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, semaine: int=None, titre: str=None, thematique: str=None):  # noqa: E501
        """Seance - a model defined in Swagger

        :param id: The id of this Seance.  # noqa: E501
        :type id: str
        :param semaine: The semaine of this Seance.  # noqa: E501
        :type semaine: int
        :param titre: The titre of this Seance.  # noqa: E501
        :type titre: str
        :param thematique: The thematique of this Seance.  # noqa: E501
        :type thematique: str
        """
        self.swagger_types = {
            'id': str,
            'semaine': int,
            'titre': str,
            'thematique': str
        }

        self.attribute_map = {
            'id': 'id',
            'semaine': 'semaine',
            'titre': 'titre',
            'thematique': 'thematique'
        }
        self._id = id
        self._semaine = semaine
        self._titre = titre
        self._thematique = thematique

    @classmethod
    def from_dict(cls, dikt) -> 'Seance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Seance of this Seance.  # noqa: E501
        :rtype: Seance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Seance.

        Identifiant de la séance  # noqa: E501

        :return: The id of this Seance.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Seance.

        Identifiant de la séance  # noqa: E501

        :param id: The id of this Seance.
        :type id: str
        """

        self._id = id

    @property
    def semaine(self) -> int:
        """Gets the semaine of this Seance.

        Numéro de la semaine  # noqa: E501

        :return: The semaine of this Seance.
        :rtype: int
        """
        return self._semaine

    @semaine.setter
    def semaine(self, semaine: int):
        """Sets the semaine of this Seance.

        Numéro de la semaine  # noqa: E501

        :param semaine: The semaine of this Seance.
        :type semaine: int
        """

        self._semaine = semaine

    @property
    def titre(self) -> str:
        """Gets the titre of this Seance.

        Titre de la séance  # noqa: E501

        :return: The titre of this Seance.
        :rtype: str
        """
        return self._titre

    @titre.setter
    def titre(self, titre: str):
        """Sets the titre of this Seance.

        Titre de la séance  # noqa: E501

        :param titre: The titre of this Seance.
        :type titre: str
        """

        self._titre = titre

    @property
    def thematique(self) -> str:
        """Gets the thematique of this Seance.

        Thématique de la séance  # noqa: E501

        :return: The thematique of this Seance.
        :rtype: str
        """
        return self._thematique

    @thematique.setter
    def thematique(self, thematique: str):
        """Sets the thematique of this Seance.

        Thématique de la séance  # noqa: E501

        :param thematique: The thematique of this Seance.
        :type thematique: str
        """

        self._thematique = thematique
