openapi: 3.0.3
info:
  title: API de Gestion des Cours en Ligne
  version: '1.0.0'
  description: Cette API permet de gérer des cours universitaires ainsi que leurs séances associées.


servers:
  - url: http://172.16.13.39:5000


paths:
  /cours:
    get:
      summary: Obtenir la liste des cours
      operationId: swagger_server.controllers.cours_controller.cours_get
      responses:
        '200':
          description: Liste des cours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cours'
    post:
      summary: Ajouter un nouveau cours
      operationId: swagger_server.controllers.cours_controller.cours_post
      requestBody:
        description: Création d'un nouveau cours
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cours'
        required: true
      responses:
        '201':
          description: Cours ajouté
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cours'
        '400':
          description: Le sigle est requis pour ajouter un nouveau cours
        '409':
          description: Un cours avec ce sigle existe déjà

  /cours/{sigle}:
    get:
      summary: Obtenir un cours par son sigle
      operationId: swagger_server.controllers.cours_controller.cours_sigle_get
      parameters:
        - name: sigle
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails du cours
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cours'
        '404':
          description: Cours non trouvé
    put:
      summary: Mettre à jour un cours
      operationId: swagger_server.controllers.cours_controller.cours_sigle_put
      parameters:
        - name: sigle
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Mise à jour des informations d'un cours
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cours'
        required: true
      responses:
        '204':
          description: Cours mis à jour
        '404':
          description: Cours non trouvé
    delete:
      summary: Supprimer un cours
      operationId: swagger_server.controllers.cours_controller.cours_sigle_delete
      parameters:
        - name: sigle
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cours supprimé
        '404':
          description: Cours non trouvé

  /cours/{sigle}/seances:
    get:
      summary: Obtenir la liste des séances d'un cours
      operationId: swagger_server.controllers.cours_controller.cours_sigle_seances_get
      parameters:
        - name: sigle
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Liste des séances du cours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seance'
        '404':
          description: Aucune séance trouvée pour ce cours

components:
  schemas:
    Cours:
      type: object
      properties:
        sigle:
          type: string
          description: Le sigle unique du cours
        titre:
          type: string
          description: Le titre complet du cours
        description:
          type: string
          description: Description détaillée du cours
      required:
        - sigle
        - titre
        - description

    Seance:
      type: object
      properties:
        sigle:
          type: string
          description: Le sigle du cours associé à la séance
        date:
          type: string
          format: date
          description: La date de la séance
        sujet:
          type: string
          description: Le sujet de la séance
      required:
        - sigle
        - date
        - sujet
