/*
 * API de Gestion des Cours en Ligne - OpenAPI 3.0
 * Ceci est une API permettant de gérer le contenu des cours en ligne. Elle expose des fonctionnalités pour créer, consulter, mettre à jour, et supprimer des cours et leurs séances. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@exemple.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Seance
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-11T15:14:48.525836921Z[GMT]")

public class Seance {
  @SerializedName("id")
  private String id = null;

  @SerializedName("semaine")
  private Integer semaine = null;

  @SerializedName("titre")
  private String titre = null;

  @SerializedName("thematique")
  private String thematique = null;

  public Seance id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifiant de la séance
   * @return id
  **/
  @Schema(description = "Identifiant de la séance")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Seance semaine(Integer semaine) {
    this.semaine = semaine;
    return this;
  }

   /**
   * Numéro de la semaine
   * @return semaine
  **/
  @Schema(description = "Numéro de la semaine")
  public Integer getSemaine() {
    return semaine;
  }

  public void setSemaine(Integer semaine) {
    this.semaine = semaine;
  }

  public Seance titre(String titre) {
    this.titre = titre;
    return this;
  }

   /**
   * Titre de la séance
   * @return titre
  **/
  @Schema(description = "Titre de la séance")
  public String getTitre() {
    return titre;
  }

  public void setTitre(String titre) {
    this.titre = titre;
  }

  public Seance thematique(String thematique) {
    this.thematique = thematique;
    return this;
  }

   /**
   * Thématique de la séance
   * @return thematique
  **/
  @Schema(description = "Thématique de la séance")
  public String getThematique() {
    return thematique;
  }

  public void setThematique(String thematique) {
    this.thematique = thematique;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Seance seance = (Seance) o;
    return Objects.equals(this.id, seance.id) &&
        Objects.equals(this.semaine, seance.semaine) &&
        Objects.equals(this.titre, seance.titre) &&
        Objects.equals(this.thematique, seance.thematique);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, semaine, titre, thematique);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Seance {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    semaine: ").append(toIndentedString(semaine)).append("\n");
    sb.append("    titre: ").append(toIndentedString(titre)).append("\n");
    sb.append("    thematique: ").append(toIndentedString(thematique)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
